### ISSUE TITLE
ic-cdk 0.13.3 breaks semver compatibility

### ISSUE THREAD

**Issue by ufoscout** [dfinity/cdk-rs#493]
`pocket-ic` 3.1.0 build fails when upgrading `ic-cdk` from 0.13.2 to 0.13.3. This is caused by #483 which introduced an API breaking change:
```sh
error[E0063]: missing field `wasm_memory_limit` in initializer of `CanisterSettings`
   --> /home/???/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-3.1.0/src/lib.rs:829:24
    |
829 |         let settings = CanisterSettings {
    |                        ^^^^^^^^^^^^^^^^ missing `wasm_memory_limit`
```

**Comment by lwshang** [comment]
Since `ic-cdk` v0.18, the Management Canister types has been factored out into a separate crate [`ic-management-canister-types`](https://crates.io/crates/ic-management-canister-types).

We will make sure that such breaking changes will be correctly reflected in the semver of both the new crate and `ic-cdk`.
